Add films_with_biggest_crew, films_in_each_language, most_popular_directors, directors_with_biggest_amount_of_genres records
C0l1ns/BigDataProject pull request #8
Opened 2023-12-12 19:40 UTC by DanyloSarvasNulp

2023-12-12 20:06 UTC, velychkovych requested changes
Wait until auto import branch will be merged, merge main into your branch and update this PR.

2023-12-12 20:10 UTC, velychkovych requested changes

2023-12-12 20:10 UTC, velychkovych commented on reports.py
> +            f.col("nb.primaryName"),
Here the same as comment above.

2023-12-12 20:10 UTC, velychkovych commented on reports.py
> +            f.col("nb.primaryName"),
Here the same as comment above.

2023-12-12 20:10 UTC, velychkovych commented on reports.py
> +            f.col("a.language"),
I would add an alias to this column, but it's up to you.

2023-12-13 07:52 UTC, C0l1ns approved these changes

2023-12-13 08:03 UTC, merged